version: '0.0.{build}'
# options
skip_branch_with_pr: true

install:
  - cinst winrar

build: off

test_script:
  - cmd: ECHO this is batch
  - ps: echo $(env_test)
  - ps: Write-Host "This is PowerShell"
  - ps: Get-ChildItem env:
